"""Generates a harness that runs the scorer's multiply and reduction under GPGPU-Sim.

GPGPU-Sim reaches cuBLAS only through a static link, which is a C++ link-time arrangement that
the bindings the scorer uses cannot take. The harness is therefore C++, and it takes the kernel
from the Java file rather than a copy so the two cannot drift apart. The multiply is written out
here, and checked against the arguments the Java passes.
"""

import pathlib
import re
import sys

SCORER = pathlib.Path(__file__).parents[3] / (
    "src/main/java/com/uber/ussi/searchablestructure/index/matrix/CudaMatrixDotProductScorer.java"
)


def read_reduction_source(scorer_text):
    """Returns the kernel the scorer compiles, taken from the Java string it is written as."""
    body = re.search(
        r"REDUCTION_SOURCE\s*=\s*(.*?);\n", scorer_text, re.DOTALL
    ).group(1)
    pieces = re.findall(r'"((?:[^"\\]|\\.)*)"', body)
    return "".join(pieces).encode().decode("unicode_escape")


def read_int_constant(scorer_text, name):
    """Returns the value of a named int constant the scorer declares."""
    return int(re.search(rf"{name} = (\d+);", scorer_text).group(1))


HARNESS = r"""
// Runs the scorer's multiply and reduction, and checks what they keep against a reference
// computed on the host. Generated by generate_harness.py; edit that instead.
#include <cublas_v2.h>
#include <cuda_runtime.h>
#include <algorithm>
#include <cmath>
#include <cstdio>
#include <vector>

%(kernel)s

#define CHECK(call) \
  do { \
    cudaError_t status = (call); \
    if (status != cudaSuccess) { \
      printf("FAIL %%s at line %%d\n", cudaGetErrorString(status), __LINE__); \
      return 1; \
    } \
  } while (0)

static const int NUM_THREADS_PER_BLOCK = %(numThreadsPerBlock)d;

int main() {
  // Small enough to simulate in reasonable time, large enough that the reduction spans warps.
  const int numRows = 512;
  const int dimension = 8;
  const int numQueries = 3;
  const int numKept = 4;

  std::vector<float> matrix((size_t) numRows * dimension);
  std::vector<double> rowUniValues(numRows);
  std::vector<float> queries((size_t) numQueries * dimension);
  std::vector<double> queryUniValues(numQueries);

  // A fixed generator, so a failure can be reproduced.
  unsigned seed = 12345;
  auto next = [&seed]() {
    seed = seed * 1103515245u + 12345u;
    return (float) ((seed >> 16) %% 1000) / 1000.0f - 0.5f;
  };
  for (int row = 0; row < numRows; ++row) {
    double sumOfSquares = 0.0;
    for (int d = 0; d < dimension; ++d) {
      float value = next();
      matrix[(size_t) row * dimension + d] = value;
      sumOfSquares += (double) value * value;
    }
    rowUniValues[row] = sumOfSquares;
  }
  // Every tenth row is deleted, which a unilateral value that is not a number marks.
  for (int row = 0; row < numRows; row += 10) {
    rowUniValues[row] = nan("");
  }
  for (int query = 0; query < numQueries; ++query) {
    double sumOfSquares = 0.0;
    for (int d = 0; d < dimension; ++d) {
      float value = next();
      queries[(size_t) query * dimension + d] = value;
      sumOfSquares += (double) value * value;
    }
    queryUniValues[query] = sumOfSquares;
  }

  float* deviceMatrix;
  float* deviceQueries;
  float* deviceProducts;
  double* deviceRowUniValues;
  double* deviceQueryUniValues;
  unsigned char* deviceTaken;
  long long* deviceKeptRowNums;
  float* deviceKeptSimilarities;
  CHECK(cudaMalloc(&deviceMatrix, sizeof(float) * numRows * dimension));
  CHECK(cudaMalloc(&deviceQueries, sizeof(float) * numQueries * dimension));
  CHECK(cudaMalloc(&deviceProducts, sizeof(float) * numQueries * numRows));
  CHECK(cudaMalloc(&deviceRowUniValues, sizeof(double) * numRows));
  CHECK(cudaMalloc(&deviceQueryUniValues, sizeof(double) * numQueries));
  CHECK(cudaMalloc(&deviceTaken, (size_t) numQueries * numRows));
  CHECK(cudaMalloc(&deviceKeptRowNums, sizeof(long long) * numQueries * numKept));
  CHECK(cudaMalloc(&deviceKeptSimilarities, sizeof(float) * numQueries * numKept));
  CHECK(cudaMemcpy(deviceMatrix, matrix.data(), sizeof(float) * numRows * dimension,
                   cudaMemcpyHostToDevice));
  CHECK(cudaMemcpy(deviceQueries, queries.data(), sizeof(float) * numQueries * dimension,
                   cudaMemcpyHostToDevice));
  CHECK(cudaMemcpy(deviceRowUniValues, rowUniValues.data(), sizeof(double) * numRows,
                   cudaMemcpyHostToDevice));
  CHECK(cudaMemcpy(deviceQueryUniValues, queryUniValues.data(), sizeof(double) * numQueries,
                   cudaMemcpyHostToDevice));

  cublasHandle_t handle;
  if (cublasCreate(&handle) != CUBLAS_STATUS_SUCCESS) {
    printf("FAIL could not create a cuBLAS handle\n");
    return 1;
  }
  // The arguments the scorer passes: the rows are row-major and cuBLAS is column-major, so they
  // read as their own transpose and the row count is the leading dimension of the products.
  const float one = 1.0f;
  const float zero = 0.0f;
  if (cublasSgemm(handle, CUBLAS_OP_T, CUBLAS_OP_N, numRows, numQueries, dimension, &one,
                  deviceMatrix, dimension, deviceQueries, dimension, &zero, deviceProducts,
                  numRows) != CUBLAS_STATUS_SUCCESS) {
    printf("FAIL the multiply did not run\n");
    return 1;
  }

  keepBestRows<<<numQueries, NUM_THREADS_PER_BLOCK>>>(
      deviceProducts, deviceRowUniValues, deviceQueryUniValues, deviceTaken, numRows, numKept,
      deviceKeptRowNums, deviceKeptSimilarities);
  CHECK(cudaDeviceSynchronize());

  std::vector<long long> keptRowNums((size_t) numQueries * numKept);
  std::vector<float> keptSimilarities((size_t) numQueries * numKept);
  CHECK(cudaMemcpy(keptRowNums.data(), deviceKeptRowNums,
                   sizeof(long long) * numQueries * numKept, cudaMemcpyDeviceToHost));
  CHECK(cudaMemcpy(keptSimilarities.data(), deviceKeptSimilarities,
                   sizeof(float) * numQueries * numKept, cudaMemcpyDeviceToHost));

  // The reference: every similarity on the host, sorted, with the deleted rows dropped.
  int numWrong = 0;
  for (int query = 0; query < numQueries; ++query) {
    std::vector<std::pair<float, int>> reference;
    for (int row = 0; row < numRows; ++row) {
      if (std::isnan(rowUniValues[row])) {
        continue;
      }
      double product = 0.0;
      for (int d = 0; d < dimension; ++d) {
        product += (double) queries[(size_t) query * dimension + d]
            * matrix[(size_t) row * dimension + d];
      }
      float similarity =
          (float) -(queryUniValues[query] + rowUniValues[row] - 2.0 * product);
      reference.push_back({similarity, row});
    }
    std::sort(reference.begin(), reference.end(),
              [](const std::pair<float, int>& a, const std::pair<float, int>& b) {
                return a.first > b.first;
              });
    for (int kept = 0; kept < numKept; ++kept) {
      long long gotRow = keptRowNums[(size_t) query * numKept + kept];
      float gotSimilarity = keptSimilarities[(size_t) query * numKept + kept];
      int wantRow = reference[kept].second;
      float wantSimilarity = reference[kept].first;
      // The multiply accumulates in a different order than the reference, so the similarities
      // are compared with a tolerance, and the rows are compared exactly.
      bool sameRow = gotRow == wantRow;
      bool sameSimilarity = fabsf(gotSimilarity - wantSimilarity) <= 1e-3f;
      if (!sameRow || !sameSimilarity) {
        ++numWrong;
        printf("query %%d rank %%d: kept row %%lld at %%f, wanted row %%d at %%f\n", query, kept,
               gotRow, gotSimilarity, wantRow, wantSimilarity);
      }
    }
  }

  cublasDestroy(handle);
  cudaFree(deviceMatrix);
  cudaFree(deviceQueries);
  cudaFree(deviceProducts);
  cudaFree(deviceRowUniValues);
  cudaFree(deviceQueryUniValues);
  cudaFree(deviceTaken);
  cudaFree(deviceKeptRowNums);
  cudaFree(deviceKeptSimilarities);

  if (numWrong == 0) {
    printf("PASS every kept row matches the host\n");
    return 0;
  }
  printf("FAIL %%d kept rows differ from the host\n", numWrong);
  return 1;
}
"""


def check_multiply_matches(scorer_text):
    """Raises when the multiply written into the harness is not the one the scorer performs."""
    java = re.sub(r"\s+", " ", scorer_text)
    expected = ("handle, CUBLAS_OP_T, CUBLAS_OP_N, numRows, numQueries, dimension, one, "
                "deviceMatrix, dimension, deviceQueries, dimension, zero, deviceProducts, "
                "numRows")
    if expected not in java:
        raise AssertionError(
            "The scorer's multiply has changed, so the harness would check a different one. "
            "Update the cublasSgemm call in HARNESS to match, then update this expectation.")


def main():
    scorer_text = SCORER.read_text()
    check_multiply_matches(scorer_text)
    kernel = read_reduction_source(scorer_text)
    # The harness launches the kernel by name, which needs it compiled rather than named by a
    # string, so the extern "C" the runtime compiler wants is dropped.
    kernel = kernel.replace('extern "C" __global__', "__global__")
    numThreadsPerBlock = read_int_constant(scorer_text, "NUM_THREADS_PER_BLOCK")
    out = pathlib.Path(__file__).parent / "harness.cu"
    out.write_text(
        HARNESS % {"kernel": kernel, "numThreadsPerBlock": numThreadsPerBlock}
    )
    print(f"wrote {out} with a {numThreadsPerBlock} thread block")


if __name__ == "__main__":
    sys.exit(main())
