"""Generates a harness that runs the scorer's multiply and select on a GPU.

The harness is C++, so that it can be run wherever a GPU is without the bindings or a JVM. It
takes the kernel from the Java file rather than a copy so the two cannot drift apart, and the
multiply is written out here and checked against the arguments the Java passes.

Defining USE_CUBLAS performs the multiply with the library, as the scorer does. Leaving it
undefined substitutes a multiply written here that produces what the cuBLAS call is specified
to produce, which exercises the select alone, the part that is hand written.
"""

import pathlib
import re
import sys

SCORER = pathlib.Path(__file__).parents[3] / (
    "src/main/java/com/uber/ussi/searchablestructure/index/matrix/CudaMatrixDotProductScorer.java"
)


def read_reduction_source(scorer_text):
    """Returns the kernel the scorer compiles, taken from the Java string it is written as."""
    body = re.search(
        r"REDUCTION_SOURCE\s*=\s*(.*?);\n", scorer_text, re.DOTALL
    ).group(1)
    pieces = re.findall(r'"((?:[^"\\]|\\.)*)"', body)
    return "".join(pieces).encode().decode("unicode_escape")


def read_int_constant(scorer_text, name):
    """Returns the value of a named int constant the scorer declares."""
    return int(re.search(rf"{name} = (\d+);", scorer_text).group(1))


def check_multiply_matches(scorer_text):
    """Raises when the multiply written into the harness is not the one the scorer performs."""
    java = re.sub(r"\s+", " ", scorer_text)
    expected = ("handle, CUBLAS_OP_T, CUBLAS_OP_N, numRows, numQueries, dimension, one, "
                "deviceMatrix, dimension, deviceQueries, dimension, zero, deviceProducts, "
                "numRows")
    if expected not in java:
        raise AssertionError(
            "The scorer's multiply has changed, so the harness would check a different one. "
            "Update the cublasSgemm call in HARNESS to match, then update this expectation.")


HARNESS = r"""
// Runs the scorer's multiply and select, and checks what they keep against a reference
// computed on the host. Generated by generate_harness.py; edit that instead.
#ifdef USE_CUBLAS
#include <cublas_v2.h>
#endif
#include <cuda_runtime.h>
#include <algorithm>
#include <cmath>
#include <cstdio>
#include <vector>

%(kernel)s

#ifndef USE_CUBLAS
// What the cublasSgemm call below is specified to leave behind: a products matrix of one row
// per query, each holding that query's dot product with every row of the matrix. Plain on
// purpose, since it stands in for the library rather than competing with it.
__global__ void multiplyQueries(const float* matrix, const float* queries, float* products,
                                int numRows, int dimension, int numQueries) {
  int row = blockIdx.x * blockDim.x + threadIdx.x;
  if (row >= numRows) {
    return;
  }
  for (int query = 0; query < numQueries; ++query) {
    float product = 0.0f;
    for (int d = 0; d < dimension; ++d) {
      product += queries[(long long) query * dimension + d]
          * matrix[(long long) row * dimension + d];
    }
    products[(long long) query * numRows + row] = product;
  }
}
#endif

#define CHECK(call) \
  do { \
    cudaError_t status = (call); \
    if (status != cudaSuccess) { \
      printf("FAIL %%s at line %%d\n", cudaGetErrorString(status), __LINE__); \
      return 1; \
    } \
  } while (0)

static const int NUM_THREADS_PER_BLOCK = %(numThreadsPerBlock)d;

int main() {
  // Small enough to check by hand, large enough that the select spans several passes.
  const int numRows = 512;
  const int dimension = 8;
  const int numQueries = 3;
  const int numKept = 4;

  std::vector<float> matrix((size_t) numRows * dimension);
  std::vector<float> rowUniValues(numRows);
  std::vector<float> queries((size_t) numQueries * dimension);
  std::vector<float> queryUniValues(numQueries);

  // A fixed generator, so a failure can be reproduced.
  unsigned seed = 12345;
  auto next = [&seed]() {
    seed = seed * 1103515245u + 12345u;
    return (float) ((seed >> 16) %% 1000) / 1000.0f - 0.5f;
  };
  for (int row = 0; row < numRows; ++row) {
    double sumOfSquares = 0.0;
    for (int d = 0; d < dimension; ++d) {
      float value = next();
      matrix[(size_t) row * dimension + d] = value;
      sumOfSquares += (double) value * value;
    }
    rowUniValues[row] = (float) sumOfSquares;
  }
  // Every tenth row is deleted, which a unilateral value that is not a number marks.
  for (int row = 0; row < numRows; row += 10) {
    rowUniValues[row] = nanf("");
  }
  for (int query = 0; query < numQueries; ++query) {
    double sumOfSquares = 0.0;
    for (int d = 0; d < dimension; ++d) {
      float value = next();
      queries[(size_t) query * dimension + d] = value;
      sumOfSquares += (double) value * value;
    }
    queryUniValues[query] = (float) sumOfSquares;
  }

  float* deviceMatrix;
  float* deviceQueries;
  float* deviceProducts;
  float* deviceRowUniValues;
  float* deviceQueryUniValues;
  long long* deviceKeptRowNums;
  float* deviceKeptDotProducts;
  CHECK(cudaMalloc(&deviceMatrix, sizeof(float) * numRows * dimension));
  CHECK(cudaMalloc(&deviceQueries, sizeof(float) * numQueries * dimension));
  CHECK(cudaMalloc(&deviceProducts, sizeof(float) * numQueries * numRows));
  CHECK(cudaMalloc(&deviceRowUniValues, sizeof(float) * numRows));
  CHECK(cudaMalloc(&deviceQueryUniValues, sizeof(float) * numQueries));
  CHECK(cudaMalloc(&deviceKeptRowNums, sizeof(long long) * numQueries * numKept));
  CHECK(cudaMalloc(&deviceKeptDotProducts, sizeof(float) * numQueries * numKept));
  CHECK(cudaMemcpy(deviceMatrix, matrix.data(), sizeof(float) * numRows * dimension,
                   cudaMemcpyHostToDevice));
  CHECK(cudaMemcpy(deviceQueries, queries.data(), sizeof(float) * numQueries * dimension,
                   cudaMemcpyHostToDevice));
  CHECK(cudaMemcpy(deviceRowUniValues, rowUniValues.data(), sizeof(float) * numRows,
                   cudaMemcpyHostToDevice));
  CHECK(cudaMemcpy(deviceQueryUniValues, queryUniValues.data(), sizeof(float) * numQueries,
                   cudaMemcpyHostToDevice));

#ifdef USE_CUBLAS
  cublasHandle_t handle;
  if (cublasCreate(&handle) != CUBLAS_STATUS_SUCCESS) {
    printf("FAIL could not create a cuBLAS handle\n");
    return 1;
  }
  // The arguments the scorer passes: the rows are row-major and cuBLAS is column-major, so they
  // read as their own transpose and the row count is the leading dimension of the products.
  const float one = 1.0f;
  const float zero = 0.0f;
  if (cublasSgemm(handle, CUBLAS_OP_T, CUBLAS_OP_N, numRows, numQueries, dimension, &one,
                  deviceMatrix, dimension, deviceQueries, dimension, &zero, deviceProducts,
                  numRows) != CUBLAS_STATUS_SUCCESS) {
    printf("FAIL the multiply did not run\n");
    return 1;
  }
#else
  multiplyQueries<<<(numRows + 127) / 128, 128>>>(deviceMatrix, deviceQueries, deviceProducts,
                                                  numRows, dimension, numQueries);
  CHECK(cudaGetLastError());
#endif

  keepBestRows<<<numQueries, NUM_THREADS_PER_BLOCK>>>(
      deviceProducts, deviceRowUniValues, deviceQueryUniValues, numRows, numKept,
      deviceKeptRowNums, deviceKeptDotProducts);
  CHECK(cudaGetLastError());
  CHECK(cudaDeviceSynchronize());

  std::vector<long long> keptRowNums((size_t) numQueries * numKept);
  std::vector<float> keptDotProducts((size_t) numQueries * numKept);
  CHECK(cudaMemcpy(keptRowNums.data(), deviceKeptRowNums,
                   sizeof(long long) * numQueries * numKept, cudaMemcpyDeviceToHost));
  CHECK(cudaMemcpy(keptDotProducts.data(), deviceKeptDotProducts,
                   sizeof(float) * numQueries * numKept, cudaMemcpyDeviceToHost));

  // The reference: every similarity on the host, sorted, with the deleted rows dropped.
  int numWrong = 0;
  for (int query = 0; query < numQueries; ++query) {
    std::vector<std::pair<float, int>> reference;
    for (int row = 0; row < numRows; ++row) {
      if (std::isnan(rowUniValues[row])) {
        continue;
      }
      double product = 0.0;
      for (int d = 0; d < dimension; ++d) {
        product += (double) queries[(size_t) query * dimension + d]
            * matrix[(size_t) row * dimension + d];
      }
      // What the select ranks by, which is the squared distance negated.
      float rankValue =
          (float) -((double) queryUniValues[query] + rowUniValues[row] - 2.0 * product);
      reference.push_back({rankValue, row});
    }
    std::sort(reference.begin(), reference.end(),
              [](const std::pair<float, int>& a, const std::pair<float, int>& b) {
                return a.first > b.first;
              });
    // The select keeps the best rows in no particular order, so what it kept is ordered here
    // before being compared rank by rank.
    // What the kernel writes is a dot product, so what it ranked by is taken back from it.
    std::vector<std::pair<float, long long>> kept;
    for (int slot = 0; slot < numKept; ++slot) {
      long long row = keptRowNums[(size_t) query * numKept + slot];
      if (row >= 0) {
        float dotProduct = keptDotProducts[(size_t) query * numKept + slot];
        float rankValue =
            (float) -((double) queryUniValues[query] + rowUniValues[row] - 2.0 * dotProduct);
        kept.push_back({rankValue, row});
      }
    }
    std::sort(kept.begin(), kept.end(),
              [](const std::pair<float, long long>& a, const std::pair<float, long long>& b) {
                return a.first > b.first;
              });
    int numWanted = std::min(numKept, (int) reference.size());
    if ((int) kept.size() != numWanted) {
      ++numWrong;
      printf("query %%d kept %%d rows, wanted %%d\n", query, (int) kept.size(), numWanted);
      continue;
    }
    // Rows ranking equally are interchangeable, so the check is that the rows kept rank
    // highest, and that each is distinct, alive, and reported with the dot product it has.
    for (int rank = 0; rank < numWanted; ++rank) {
      if (fabsf(kept[rank].first - reference[rank].first) > 1e-3f) {
        ++numWrong;
        printf("query %%d rank %%d: kept %%f, wanted %%f\n", query, rank, kept[rank].first,
               reference[rank].first);
      }
    }
    for (int rank = 0; rank < numWanted; ++rank) {
      long long row = kept[rank].second;
      if (row < 0 || row >= numRows || std::isnan(rowUniValues[row])) {
        ++numWrong;
        printf("query %%d rank %%d: kept row %%lld, which is out of range or deleted\n", query,
               rank, row);
        continue;
      }
      for (int other = 0; other < rank; ++other) {
        if (kept[other].second == row) {
          ++numWrong;
          printf("query %%d: kept row %%lld twice\n", query, row);
        }
      }
      double product = 0.0;
      for (int d = 0; d < dimension; ++d) {
        product += (double) queries[(size_t) query * dimension + d]
            * matrix[(size_t) row * dimension + d];
      }
      float rankValue =
          (float) -((double) queryUniValues[query] + rowUniValues[row] - 2.0 * product);
      if (fabsf(kept[rank].first - rankValue) > 1e-3f) {
        ++numWrong;
        printf("query %%d: row %%lld reported %%f but has %%f\n", query, row, kept[rank].first,
               rankValue);
      }
    }
  }

#ifdef USE_CUBLAS
  cublasDestroy(handle);
#endif
  cudaFree(deviceMatrix);
  cudaFree(deviceQueries);
  cudaFree(deviceProducts);
  cudaFree(deviceRowUniValues);
  cudaFree(deviceQueryUniValues);
  cudaFree(deviceKeptRowNums);
  cudaFree(deviceKeptDotProducts);

  if (numWrong == 0) {
    printf("PASS every kept row matches the host\n");
    return 0;
  }
  printf("FAIL %%d kept rows differ from the host\n", numWrong);
  return 1;
}
"""


def main():
    scorer_text = SCORER.read_text()
    check_multiply_matches(scorer_text)
    kernel = read_reduction_source(scorer_text)
    # The harness launches the kernel by name, which needs it compiled rather than named by a
    # string, so the extern "C" the runtime compiler wants is dropped.
    kernel = kernel.replace('extern "C" __global__', "__global__")
    numThreadsPerBlock = read_int_constant(scorer_text, "NUM_THREADS_PER_BLOCK")
    out = pathlib.Path(__file__).parent / "harness.cu"
    out.write_text(
        HARNESS % {"kernel": kernel, "numThreadsPerBlock": numThreadsPerBlock}
    )
    print(f"wrote {out} with a {numThreadsPerBlock} thread block")


if __name__ == "__main__":
    sys.exit(main())
